name: Build & Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true

  release:
    needs: create-draft-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [donkey, three-little-pigs, omnomcom]
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Copy ${{ matrix.config }}-window-definitions.json to window-definitions.json
        shell: bash
        run: |
          cp window-definitions/${{ matrix.config }}-window-definitions.json window-definitions.json

      - name: Build and Publish ${{ matrix.config }}
        run: |
          npx electron-builder install-app-deps
          npx electron-builder --publish always --config build-config/electron-builder-${{ matrix.config }}.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-draft-release:
    needs: [create-draft-release, release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish Draft Release
        uses: softprops/action-gh-release@v3
        with:
          draft: false